<?php

return [
    [
        'apartment_id' => '0',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '1',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '2',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '3',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '4',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '5',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '6',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '7',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '8',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '9',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '10',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '11',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '12',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '13',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '14',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '15',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '16',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '17',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '18',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '19',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '20',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '21',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '22',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '23',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '24',
        'street'       => 'Via S. Gaetano',
        'zip'          => '16031',
        'city'         => 'Pieve Ligure, Liguria',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '25',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '26',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '27',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '28',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '29',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '30',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '31',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '32',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '33',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '34',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '35',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '36',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '37',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '38',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '39',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '40',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '41',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '42',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '43',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '44',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '45',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '46',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '47',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '48',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
    [
        'apartment_id' => '49',
        'street'       => '',
        'zip'          => '',
        'city'         => '',
        'latitude'     => '',
        'longitude'    => '',
    ],
];
