<?php

return [
    [
        'id'            => 0,
        'name'          => 'Cozy Studio Apartment',
        'rooms'         => 1,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 35,
        'is_available'  => true,
        'is_sponsored'  => true,
        'user_id'       => 1,
    ],
    [
        'id'            => 1,
        'name'          => 'Spacious 2-Bedroom Apartment',
        'rooms'         => 3,
        'beds'          => 2,
        'bathrooms'     => 2,
        'square_meters' => 85,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 1,
    ],
    [
        'id'            => 2,
        'name'          => 'Luxury Penthouse Suite',
        'rooms'         => 4,
        'beds'          => 3,
        'bathrooms'     => 3,
        'square_meters' => 180,
        'is_available'  => true,
        'is_sponsored'  => true,
        'user_id'       => 1,
    ],
    [
        'id'            => 3,
        'name'          => 'Charming Garden Apartment',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 55,
        'is_available'  => false,
        'is_sponsored'  => false,
        'user_id'       => 5,
    ],
    [
        'id'            => 4,
        'name'          => 'Seaside Beach House',
        'rooms'         => 5,
        'beds'          => 4,
        'bathrooms'     => 3,
        'square_meters' => 200,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 5,
    ],
    [
        'id'            => 5,
        'name'          => 'Mountain View Cabin',
        'rooms'         => 3,
        'beds'          => 2,
        'bathrooms'     => 2,
        'square_meters' => 120,
        'is_available'  => true,
        'is_sponsored'  => true,
        'user_id'       => 5,
    ],
    [
        'id'            => 6,
        'name'          => 'Downtown Loft Apartment',
        'rooms'         => 1,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 40,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 7,
    ],
    [
        'id'            => 7,
        'name'          => 'Rural Farmhouse Retreat',
        'rooms'         => 4,
        'beds'          => 3,
        'bathrooms'     => 2,
        'square_meters' => 150,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 7,
    ],
    [
        'id'            => 8,
        'name'          => 'Sunny Beachfront Condo',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 60,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 7,
    ],
    [
        'id'            => 9,
        'name'          => 'Historic City Center Apartment',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 65,
        'is_available'  => false,
        'is_sponsored'  => false,
        'user_id'       => 4,
    ],
    [
        'id'            => 10,
        'name'          => 'Riverside Cabin Retreat',
        'rooms'         => 3,
        'beds'          => 2,
        'bathrooms'     => 1,
        'square_meters' => 80,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 4,
    ],
    [
        'id'            => 11,
        'name'          => 'Urban Studio Loft',
        'rooms'         => 1,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 45,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 4,
    ],
    [
        'id'            => 12,
        'name'          => 'Secluded Lakeside Cottage',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 70,
        'is_available'  => false,
        'is_sponsored'  => false,
        'user_id'       => 19,
    ],
    [
        'id'            => 13,
        'name'          => 'Mountain Retreat Chalet',
        'rooms'         => 3,
        'beds'          => 2,
        'bathrooms'     => 2,
        'square_meters' => 100,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 19,
    ],
    [
        'id'            => 14,
        'name'          => 'Downtown Luxury Penthouse',
        'rooms'         => 4,
        'beds'          => 3,
        'bathrooms'     => 3,
        'square_meters' => 180,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 19,
    ],
    [
        'id'            => 15,
        'name'          => 'City View Apartment',
        'rooms'         => 2,
        'beds'          => 2,
        'bathrooms'     => 2,
        'square_meters' => 75,
        'is_available'  => false,
        'is_sponsored'  => false,
        'user_id'       => 15,
    ],
    [
        'id'            => 16,
        'name'          => 'Countryside Villa',
        'rooms'         => 5,
        'beds'          => 4,
        'bathrooms'     => 3,
        'square_meters' => 220,
        'is_available'  => true,
        'is_sponsored'  => true,
        'user_id'       => 15,
    ],
    [
        'id'            => 17,
        'name'          => 'Oceanfront Paradise',
        'rooms'         => 3,
        'beds'          => 2,
        'bathrooms'     => 2,
        'square_meters' => 120,
        'is_available'  => true,
        'is_sponsored'  => true,
        'user_id'       => 15,
    ],
    [
        'id'            => 18,
        'name'          => 'Downtown Loft',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 60,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 8,
    ],
    [
        'id'            => 19,
        'name'          => 'Riverside Cabin',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 70,
        'is_available'  => false,
        'is_sponsored'  => false,
        'user_id'       => 8,
    ],
    [
        'id'            => 20,
        'name'          => 'Mountain View Chalet',
        'rooms'         => 3,
        'beds'          => 2,
        'bathrooms'     => 2,
        'square_meters' => 100,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 8,
    ],
    [
        'id'            => 21,
        'name'          => 'Beachfront Bungalow',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 65,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 8,
    ],
    [
        'id'            => 22,
        'name'          => 'Mountain Retreat Cabin',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 75,
        'is_available'  => false,
        'is_sponsored'  => false,
        'user_id'       => 11,
    ],
    [
        'id'            => 23,
        'name'          => 'Lakeside Cottage',
        'rooms'         => 3,
        'beds'          => 2,
        'bathrooms'     => 2,
        'square_meters' => 100,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 11,
    ],
    [
        'id'            => 24,
        'name'          => 'Luxury Villa with Pool',
        'rooms'         => 6,
        'beds'          => 4,
        'bathrooms'     => 5,
        'square_meters' => 350,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 0,
    ],
    [
        'id'            => 25,
        'name'          => 'Downtown Studio Apartment',
        'rooms'         => 1,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 40,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 11,
    ],
    [
        'id'            => 26,
        'name'          => 'Forest Retreat Cabin',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 60,
        'is_available'  => false,
        'is_sponsored'  => true,
        'user_id'       => 11,
    ],
    [
        'id'            => 27,
        'name'          => 'Seaside Apartment with a View',
        'rooms'         => 2,
        'beds'          => 1,
        'bathrooms'     => 1,
        'square_meters' => 65,
        'is_available'  => false,
        'is_sponsored'  => false,
        'user_id'       => 16,
    ],
    [
        'id'            => 28,
        'name'          => 'Rustic Mountain Cabin',
        'rooms'         => 3,
        'beds'          => 2,
        'bathrooms'     => 2,
        'square_meters' => 80,
        'is_available'  => true,
        'is_sponsored'  => false,
        'user_id'       => 16,
    ],
    [
        'id'            => 29,
        'name'          => 'Beachfront Paradise Villa',
        'rooms'         => 4,
        'beds'          => 3,
        'bathrooms'     => 3,
        'square_meters' => 220,
        'is_available'  => true,
        'is_sponsored'  => true,
        'user_id'       => 16,
    ],
];
