<?php

return [
    [
        'id'            => '0',
        'name'          => 'Villa Scirocco 10+2, Emma Villas',
        'rooms'         => '5',
        'beds'          => '7',
        'bathrooms'     => '4',
        'square_meters' => '270',
        'is_available'  => false,
        'user_id'       => [1],
    ],
    [
        'id'            => '1',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [1],
    ],
    [
        'id'            => '2',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [1],
    ],
    [
        'id'            => '3',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [5],
    ],
    [
        'id'            => '4',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [5],
    ],
    [
        'id'            => '5',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [5],
    ],
    [
        'id'            => '6',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [7],
    ],
    [
        'id'            => '7',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [7],
    ],
    [
        'id'            => '8',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [7],
    ],
    [
        'id'            => '9',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [4],
    ],
    [
        'id'            => '10',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [4],
    ],
    [
        'id'            => '11',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [4],
    ],
    [
        'id'            => '12',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [19],
    ],
    [
        'id'            => '13',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [19],
    ],
    [
        'id'            => '14',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [19],
    ],
    [
        'id'            => '15',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [15],
    ],
    [
        'id'            => '16',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [15],
    ],
    [
        'id'            => '17',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [15],
    ],
    [
        'id'            => '18',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [8],
    ],
    [
        'id'            => '19',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [8],
    ],
    [
        'id'            => '20',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [8],
    ],
    [
        'id'            => '21',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [8],
    ],
    [
        'id'            => '22',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [11],
    ],
    [
        'id'            => '23',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [11],
    ],
    [
        'id'            => '24',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [0],
    ],
    [
        'id'            => '25',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [11],
    ],
    [
        'id'            => '26',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [11],
    ],
    [
        'id'            => '27',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [16],
    ],
    [
        'id'            => '28',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [16],
    ],
    [
        'id'            => '29',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [16],
    ],
    [
        'id'            => '30',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => false,
        'user_id'       => [16],
    ],
    [
        'id'            => '31',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [3],
    ],
    [
        'id'            => '32',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [3],
    ],
    [
        'id'            => '33',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [3],
    ],
    [
        'id'            => '34',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [9],
    ],
    [
        'id'            => '35',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [9],
    ],
    [
        'id'            => '36',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [9],
    ],
    [
        'id'            => '37',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [9],
    ],
    [
        'id'            => '38',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [10],
    ],
    [
        'id'            => '39',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [10],
    ],
    [
        'id'            => '40',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [10],
    ],
    [
        'id'            => '41',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [10],
    ],
    [
        'id'            => '42',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [10],
    ],
    [
        'id'            => '43',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [10],
    ],
    [
        'id'            => '44',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [14],
    ],
    [
        'id'            => '45',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [14],
    ],
    [
        'id'            => '46',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [14],
    ],
    [
        'id'            => '47',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [20],
    ],
    [
        'id'            => '48',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [20],
    ],
    [
        'id'            => '49',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => true,
        'user_id'       => [20],
    ],
];
