<?php

return [
    [
        'id'            => '1',
        'name'          => 'Villa Scirocco 10+2, Emma Villas',
        'rooms'         => '5',
        'beds'          => '7',
        'bathrooms'     => '4',
        'square_meters' => '120',
        'is_available'  => '1',
        'user_id'       => '1',
    ],
    [
        'id'            => '2',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '3',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '4',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '5',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '6',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '7',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '8',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '9',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '10',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '11',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '12',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '13',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '14',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '15',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '16',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '17',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '18',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '19',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '20',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '21',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '22',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '23',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '24',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '25',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '26',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '27',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '28',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '29',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '30',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '31',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '32',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '33',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '34',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '35',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '36',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '37',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '38',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '39',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '40',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '41',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '42',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '43',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '44',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '45',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '46',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '47',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '48',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '49',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
    [
        'id'            => '50',
        'name'          => '',
        'rooms'         => '',
        'beds'          => '',
        'bathrooms'     => '',
        'square_meters' => '',
        'is_available'  => '',
        'user_id'       => '',
    ],
];
