<?php

return [
    [
        'id'       => 0,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 1,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 2,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
    [
        'id'       => 3,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 4,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 5,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
    [
        'id'       => 6,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 7,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 8,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
    [
        'id'       => 9,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 10,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 11,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
    [
        'id'       => 12,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 13,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 14,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
    [
        'id'       => 15,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 16,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 17,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
    [
        'id'       => 18,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 19,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 20,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
    [
        'id'       => 21,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 22,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 23,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
    [
        'id'       => 24,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 25,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 26,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
    [
        'id'       => 27,
        'level'    => 'bronze',
        'price'    => '2.99',
        'duration' => '24',
    ],
    [
        'id'       => 28,
        'level'    => 'silver',
        'price'    => '5.99',
        'duration' => '72',
    ],
    [
        'id'       => 29,
        'level'    => 'gold',
        'price'    => '9.99',
        'duration' => '144',
    ],
];

