<?php

return [
    [
        'id'         => '0',
        'name'       => 'Carlo',
        'surname'    => 'Manconi',
        'email'      => 'carlo_manconi@gmail.com',
        'password'   => 'Carlo123',
        'date_birth' => '12/06/1966',
    ],
    [
        'id'         => '1',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '2',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '3',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '4',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '5',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '6',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '7',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '8',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '9',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '10',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '11',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '12',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '13',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '14',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '15',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '16',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '17',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '18',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '19',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '20',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '21',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '22',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '23',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '24',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '25',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '26',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '27',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '28',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '29',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
];
