<?php

return [
    [
        'id'         => '1',
        'name'       => 'Carlo',
        'surname'    => 'Manconi',
        'email'      => 'carlo_manconi@gmail.com',
        'password'   => 'Carlo123',
        'date_birth' => '12/06/1966',
    ],
    [
        'id'         => '2',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '3',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '4',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '5',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '6',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '7',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '8',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '9',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '10',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '11',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '12',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '13',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '14',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '15',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '16',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '17',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '18',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '19',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '20',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '21',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '22',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '23',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '24',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '25',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '26',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '27',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '28',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '29',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '30',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '31',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '32',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '33',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '34',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '35',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '36',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '37',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '38',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '39',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '40',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '41',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '42',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '43',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '44',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '45',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '46',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '47',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '48',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '49',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
    [
        'id'         => '50',
        'name'       => '',
        'surname'    => '',
        'email'      => '',
        'password'   => '',
        'date_birth' => '',
    ],
];
