<?php

return [
    [
        'id'         => 0,
        'name'       => 'Carlo',
        'surname'    => 'Manconi',
        'email'      => 'carlo.manconi@example.com',
        'password'   => 'Carlo123',
        'date_birth' => '12/06/1966',
    ],
    [
        'id'         => 1,
        'name'       => 'Alice',
        'surname'    => 'Johnson',
        'email'      => 'alice.johnson@example.com',
        'password'   => 'Password123',
        'date_birth' => '03/15/1985',
    ],
    [
        'id'         => 2,
        'name'       => 'Bob',
        'surname'    => 'Smith',
        'email'      => 'bob.smith@example.com',
        'password'   => 'SecurePass789',
        'date_birth' => '08/22/1990',
    ],
    [
        'id'         => 3,
        'name'       => 'Eva',
        'surname'    => 'Anderson',
        'email'      => 'eva.anderson@example.com',
        'password'   => 'EvaPass456',
        'date_birth' => '11/29/1982',
    ],
    [
        'id'         => 4,
        'name'       => 'David',
        'surname'    => 'Brown',
        'email'      => 'david.brown@example.com',
        'password'   => 'BrownPass987',
        'date_birth' => '05/10/1977',
    ],
    [
        'id'         => 5,
        'name'       => 'Sophia',
        'surname'    => 'Lee',
        'email'      => 'sophia.lee@example.com',
        'password'   => 'LeePass321',
        'date_birth' => '07/19/1995',
    ],
    [
        'id'         => 6,
        'name'       => 'Michael',
        'surname'    => 'Garcia',
        'email'      => 'michael.garcia@example.com',
        'password'   => 'GarciaPass246',
        'date_birth' => '09/14/1988',
    ],
    [
        'id'         => 7,
        'name'       => 'Olivia',
        'surname'    => 'Martinez',
        'email'      => 'olivia.martinez@example.com',
        'password'   => 'MartinezPass789',
        'date_birth' => '02/25/1993',
    ],
    [
        'id'         => 8,
        'name'       => 'James',
        'surname'    => 'Taylor',
        'email'      => 'james.taylor@example.com',
        'password'   => 'TaylorPass567',
        'date_birth' => '04/08/1976',
    ],
    [
        'id'         => 9,
        'name'       => 'Emma',
        'surname'    => 'White',
        'email'      => 'emma.white@example.com',
        'password'   => 'WhitePass123',
        'date_birth' => '01/12/1999',
    ],
    [
        'id'         => 10,
        'name'       => 'Liam',
        'surname'    => 'Thomas',
        'email'      => 'liam.thomas@example.com',
        'password'   => 'ThomasPass890',
        'date_birth' => '06/30/1980',
    ],
    [
        'id'         => 11,
        'name'       => 'Mia',
        'surname'    => 'Walker',
        'email'      => 'mia.walker@example.com',
        'password'   => 'WalkerPass456',
        'date_birth' => '10/04/1992',
    ],
    [
        'id'         => 12,
        'name'       => 'Noah',
        'surname'    => 'Johnson',
        'email'      => 'noah.johnson@example.com',
        'password'   => 'JohnsonPass789',
        'date_birth' => '12/17/1974',
    ],
    [
        'id'         => 13,
        'name'       => 'Ava',
        'surname'    => 'Harris',
        'email'      => 'ava.harris@example.com',
        'password'   => 'HarrisPass234',
        'date_birth' => '09/08/1987',
    ],
    [
        'id'         => 14,
        'name'       => 'William',
        'surname'    => 'Clark',
        'email'      => 'william.clark@example.com',
        'password'   => 'ClarkPass567',
        'date_birth' => '03/27/1991',
    ],
    [
        'id'         => 15,
        'name'       => 'Charlotte',
        'surname'    => 'Lewis',
        'email'      => 'charlotte.lewis@example.com',
        'password'   => 'LewisPass890',
        'date_birth' => '07/01/1979',
    ],
    [
        'id'         => 16,
        'name'       => 'Logan',
        'surname'    => 'King',
        'email'      => 'logan.king@example.com',
        'password'   => 'KingPass123',
        'date_birth' => '05/14/1984',
    ],
    [
        'id'         => 17,
        'name'       => 'Harper',
        'surname'    => 'Baker',
        'email'      => 'harper.baker@example.com',
        'password'   => 'BakerPass456',
        'date_birth' => '11/20/1998',
    ],
    [
        'id'         => 18,
        'name'       => 'Lucas',
        'surname'    => 'Adams',
        'email'      => 'lucas.adams@example.com',
        'password'   => 'AdamsPass789',
        'date_birth' => '02/03/1983',
    ],
    [
        'id'         => 19,
        'name'       => 'Luna',
        'surname'    => 'Parker',
        'email'      => 'luna.parker@example.com',
        'password'   => 'ParkerPass234',
        'date_birth' => '10/09/1986',
    ],
    [
        'id'         => 20,
        'name'       => 'Henry',
        'surname'    => 'Wright',
        'email'      => 'henry.wright@example.com',
        'password'   => 'WrightPass567',
        'date_birth' => '06/07/1997',
    ],
    [
        'id'         => 21,
        'name'       => 'Ella',
        'surname'    => 'Collins',
        'email'      => 'ella.collins@example.com',
        'password'   => 'CollinsPass890',
        'date_birth' => '04/23/1978',
    ],
    [
        'id'         => 22,
        'name'       => 'Alexander',
        'surname'    => 'Hall',
        'email'      => 'alexander.hall@example.com',
        'password'   => 'HallPass123',
        'date_birth' => '08/12/1994',
    ],
    [
        'id'         => 23,
        'name'       => 'Grace',
        'surname'    => 'Young',
        'email'      => 'grace.young@example.com',
        'password'   => 'YoungPass456',
        'date_birth' => '01/05/1981',
    ],
    [
        'id'         => 24,
        'name'       => 'Daniel',
        'surname'    => 'Miller',
        'email'      => 'daniel.miller@example.com',
        'password'   => 'MillerPass789',
        'date_birth' => '09/27/1975',
    ],
    [
        'id'         => 25,
        'name'       => 'Avery',
        'surname'    => 'Hill',
        'email'      => 'avery.hill@example.com',
        'password'   => 'HillPass234',
        'date_birth' => '03/08/1996',
    ],
    [
        'id'         => 26,
        'name'       => 'Jackson',
        'surname'    => 'Turner',
        'email'      => 'jackson.turner@example.com',
        'password'   => 'TurnerPass567',
        'date_birth' => '07/02/1989',
    ],
    [
        'id'         => 27,
        'name'       => 'Sofia',
        'surname'    => 'Gonzalez',
        'email'      => 'sofia.gonzalez@example.com',
        'password'   => 'GonzalezPass890',
        'date_birth' => '05/18/1987',
    ],
    [
        'id'         => 28,
        'name'       => 'Lucas',
        'surname'    => 'Scott',
        'email'      => 'lucas.scott@example.com',
        'password'   => 'ScottPass123',
        'date_birth' => '10/30/1990',
    ],
    [
        'id'         => 29,
        'name'       => 'Lily',
        'surname'    => 'Adams',
        'email'      => 'lily.adams@example.com',
        'password'   => 'AdamsPass456',
        'date_birth' => '06/12/1984',
    ],

];
